services:
  diabets-postgres:
    image: postgres
    container_name: diabets-postgres
    volumes:
      - diabets_vol:/data/postgres
    environment:
      PGDATA: /data/postgres
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - postgres
    restart: unless-stopped

  pgadmin_diabets:
    container_name: pgadmin_diabets
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    env_file:
      - .env
    volumes:
      - pgadmin_diabets_vol:/var/lib/pgadmin
    ports:
      - '${PGADMIN_PORT}:80'
    networks:
      - postgres
    restart: unless-stopped

  # diabets-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: diabets-app
  #   env_file:
  #     - .env
  #   ports:
  #     - '${SERVER_PORT}:${SERVER_PORT}'
  #   networks:
  #     - postgres
  #   restart: unless-stopped
  #   depends_on:
  #     - diabets-postgres

volumes:
  diabets_vol:
  pgadmin_diabets_vol:

networks:
  postgres:
    driver: bridge
