pipeline {
    agent any

    stages {
        stage('Navigate to the backend folder') {
            steps {
                script {
                    sh 'cd /var/lib/jenkins/workspace/DiabetsApplication/backend-diabets && ls -la'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    def imageName = "jandernery/blood-sweet-api:${env.BUILD_ID.replaceAll('[^a-zA-Z0-9_.-]', '_')}"
                    docker.build(imageName, '/var/lib/jenkins/workspace/DiabetsApplication/backend-diabets')
                }
            }
        }
        stage('Push Image') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                        def imageName = "jandernery/blood-sweet-api:${env.BUILD_ID.replaceAll('[^a-zA-Z0-9_.-]', '_')}"
                        def dockerImage = docker.image(imageName)
                        dockerImage.push()
                    }                    
                }
            }
        }
    }
}
