pipeline {
    agent any

    stages {
        stage('Navigate to the backend folder') {
            steps {
                script {
                    sh 'cd /var/lib/jenkins/workspace/DiabetsApplication/backend-diabets && ls -la'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    def imageName = "jandernery/blood-sweet-api:${env.BUILD_ID.replaceAll('[^a-zA-Z0-9_.-]', '_')}"
                    def imageNameLatest = "jandernery/blood-sweet-api:latest"
                    
                    docker.build(imageName, '/var/lib/jenkins/workspace/DiabetsApplication/backend-diabets')
                    docker.build(imageNameLatest, '/var/lib/jenkins/workspace/DiabetsApplication/backend-diabets')
                }
            }
        }

        stage('Push Image') {
            steps {
                script {
                    def imageName = "jandernery/blood-sweet-api:${env.BUILD_ID.replaceAll('[^a-zA-Z0-9_.-]', '_')}"
                    def imageLatest = "jandernery/blood-sweet-api:latest"
                    
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                        docker.image(imageName).push()
                        docker.image(imageLatest).push()
                    }
                }
            }
        }
    }
}
